name: Deploy CIPP-API to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # --- STEP DI DEBUG DA AGGIUNGERE ---
      - name: 'Debug: List resources in Resource Group'
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo "--- Sto elencando le risorse nel gruppo: AZ-LEOS-CIPP ---"
            az resource list --resource-group AZ-LEOS-CIPP -o table
            echo "-----------------------------------------------------------"
      # ------------------------------------

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: 'cipptv53y'
          package: '.'
