name: Deploy CIPP-API to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Lo step di "Login to Azure" non è più necessario con questo metodo

      - name: 'Deploy to Azure Function App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cipptv53y'
          package: '.'
          # Usiamo il nuovo segreto per un'autenticazione diretta
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
